services:

  unbound-mailcow:
    image: ghcr.io/mailcow/unbound:1.24
    environment:
      - TZ=${TZ}
      - SKIP_UNBOUND_HEALTHCHECK=${SKIP_UNBOUND_HEALTHCHECK:-n}
    volumes:
      - ./data/hooks/unbound:/hooks:Z
      - ./data/conf/unbound/unbound.conf:/etc/unbound/unbound.conf:ro,Z
    restart: always
    tty: true
    networks:
      mailcow-network:
        ipv4_address: 172.30.100.254
        aliases:
          - unbound

  mysql-mailcow:
    image: mariadb:10.11
    depends_on:
      - unbound-mailcow
      - netfilter-mailcow
    stop_grace_period: 45s
    volumes:
      - mysql-vol-1:/var/lib/mysql/
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/mysql/:/etc/mysql/conf.d/:ro,Z
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${DBROOT}
      - MYSQL_DATABASE=${DBNAME}
      - MYSQL_USER=${DBUSER}
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_INITDB_SKIP_TZINFO=1
    restart: always
    ports:
      - "${SQL_PORT:-127.0.0.1:13306}:3306"
    networks:
      mailcow-network:
        aliases:
          - mysql

  redis-mailcow:
    image: redis:7.4.2-alpine
    entrypoint: ["/bin/sh","/redis-conf.sh"]
    volumes:
      - redis-vol-1:/data/
      - ./data/conf/redis/redis-conf.sh:/redis-conf.sh:z
    restart: always
    depends_on:
      - netfilter-mailcow
    ports:
      - "${REDIS_PORT:-127.0.0.1:7654}:6379"
    environment:
      - TZ=${TZ}
      - REDISPASS=${REDISPASS}
      - REDISMASTERPASS=${REDISMASTERPASS:-}
    sysctls:
      - net.core.somaxconn=4096
    networks:
      mailcow-network:
        ipv4_address: 172.30.100.249
        aliases:
          - redis

  clamd-mailcow:
    image: ghcr.io/mailcow/clamd:1.70
    restart: always
    depends_on:
      unbound-mailcow:
        condition: service_healthy
    dns:
      - 172.30.100.254
    environment:
      - TZ=${TZ}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
    volumes:
      - ./data/conf/clamav/:/etc/clamav/:Z
      - clamd-db-vol-1:/var/lib/clamav
    networks:
      mailcow-network:
        aliases:
          - clamd

  rspamd-mailcow:
    image: ghcr.io/mailcow/rspamd:2.2
    stop_grace_period: 30s
    depends_on:
      - dovecot-mailcow
      - clamd-mailcow
    environment:
      - TZ=${TZ}
      - IPV4_NETWORK=172.30.100
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - SPAMHAUS_DQS_KEY=${SPAMHAUS_DQS_KEY:-}
    volumes:
      - ./data/hooks/rspamd:/hooks:Z
      - ./data/conf/rspamd/custom/:/etc/rspamd/custom:z
      - ./data/conf/rspamd/override.d/:/etc/rspamd/override.d:Z
      - ./data/conf/rspamd/local.d/:/etc/rspamd/local.d:Z
      - ./data/conf/rspamd/plugins.d/:/etc/rspamd/plugins.d:Z
      - ./data/conf/rspamd/lua/:/etc/rspamd/lua/:ro,Z
      - ./data/conf/rspamd/rspamd.conf.local:/etc/rspamd/rspamd.conf.local:Z
      - ./data/conf/rspamd/rspamd.conf.override:/etc/rspamd/rspamd.conf.override:Z
      - rspamd-vol-1:/var/lib/rspamd
    restart: always
    hostname: rspamd
    dns:
      - 172.30.100.254
    networks:
      mailcow-network:
        aliases:
          - rspamd

  php-fpm-mailcow:
    image: ghcr.io/mailcow/phpfpm:1.93
    command: "php-fpm -d date.timezone=${TZ} -d expose_php=0"
    depends_on:
      - redis-mailcow
    volumes:
      - ./data/hooks/phpfpm:/hooks:Z
      - ./data/web:/web:z
      - ./data/conf/rspamd/dynmaps:/dynmaps:ro,z
      - ./data/conf/rspamd/custom/:/rspamd_custom_maps:z
      - ./data/conf/dovecot/auth/mailcowauth.php:/mailcowauth/mailcowauth.php:z
      - ./data/web/inc/functions.inc.php:/mailcowauth/functions.inc.php:z
      - ./data/web/inc/functions.auth.inc.php:/mailcowauth/functions.auth.inc.php:z
      - ./data/web/inc/sessions.inc.php:/mailcowauth/sessions.inc.php:z
      - ./data/web/inc/functions.mailbox.inc.php:/mailcowauth/functions.mailbox.inc.php:z
      - ./data/web/inc/functions.ratelimit.inc.php:/mailcowauth/functions.ratelimit.inc.php:z
      - ./data/web/inc/functions.acl.inc.php:/mailcowauth/functions.acl.inc.php:z
      - rspamd-vol-1:/var/lib/rspamd
      - mysql-socket-vol-1:/var/run/mysqld/
      - ./data/conf/sogo/:/etc/sogo/:z
      - ./data/conf/rspamd/meta_exporter:/meta_exporter:ro,z
      - ./data/conf/phpfpm/crons:/crons:z
      - ./data/conf/phpfpm/sogo-sso/:/etc/sogo-sso/:z
      - ./data/conf/phpfpm/php-fpm.d/pools.conf:/usr/local/etc/php-fpm.d/z-pools.conf:Z
      - ./data/conf/phpfpm/php-conf.d/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini:Z
      - ./data/conf/phpfpm/php-conf.d/upload.ini:/usr/local/etc/php/conf.d/upload.ini:Z
      - ./data/conf/phpfpm/php-conf.d/other.ini:/usr/local/etc/php/conf.d/zzz-other.ini:Z
      - ./data/conf/dovecot/global_sieve_before:/global_sieve/before:z
      - ./data/conf/dovecot/global_sieve_after:/global_sieve/after:z
      - ./data/assets/templates:/tpls:z
      - ./data/conf/nginx/:/etc/nginx/conf.d/:z
    dns:
      - 172.30.100.254
    environment:
      - REDIS_SLAVEOF_IP=${REDIS_SLAVEOF_IP:-}
      - REDIS_SLAVEOF_PORT=${REDIS_SLAVEOF_PORT:-}
      - REDISPASS=${REDISPASS}
      - LOG_LINES=${LOG_LINES:-9999}
      - TZ=${TZ}
      - DBNAME=${DBNAME}
      - DBUSER=${DBUSER}
      - DBPASS=${DBPASS}
      - MAILCOW_HOSTNAME=${MAILCOW_HOSTNAME}
      - MAILCOW_PASS_SCHEME=${MAILCOW_PASS_SCHEME:-BLF-CRYPT}
      - IMAP_PORT=${IMAP_PORT:-143}
      - IMAPS_PORT=${IMAPS_PORT:-993}
      - POP_PORT=${POP_PORT:-110}
      - POPS_PORT=${POPS_PORT:-995}
      - SIEVE_PORT=${SIEVE_PORT:-4190}
      - IPV4_NETWORK=172.30.100
      - IPV6_NETWORK=${IPV6_NETWORK:-fd4d:6169:6c63:6f77::/64}
      - SUBMISSION_PORT=${SUBMISSION_PORT:-587}
      - SMTPS_PORT=${SMTPS_PORT:-465}
      - SMTP_PORT=${SMTP_PORT:-25}
      - API_KEY=${API_KEY:-invalid}
      - API_KEY_READ_ONLY=${API_KEY_READ_ONLY:-invalid}
      - API_ALLOW_FROM=${API_ALLOW_FROM:-invalid}
      - COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME:-mailcow-dockerized}
      - SKIP_FTS=${SKIP_FTS:-y}
      - SKIP_CLAMD=${SKIP_CLAMD:-n}
      - SKIP_OLEFY=${SKIP_OLEFY:-n}
      - SKIP_SOGO=${SKIP_SOGO:-n}
      - ALLOW_ADMIN_EMAIL_LOGIN=${ALLOW_ADMIN_EMAIL_LOGIN:-n}
      - MASTER=${MASTER:-y}
      - DEV_MODE=${DEV_MODE:-n}
      - DEMO_MODE=${DEMO_MODE:-n}
      - WEBAUTHN_ONLY_TRUSTED_VENDORS=${WEBAUTHN_ONLY_TRUSTED_VENDORS:-n}
      - CLUSTERMODE=${CLUSTERMODE:-}
      - ADDITIONAL_SERVER_NAMES=${ADDITIONAL_SERVER_NAMES:-}
    restart: always
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.phpfpm_keycloak_sync.schedule: "@every 1m"
      ofelia.job-exec.phpfpm_keycloak_sync.no-overlap: "true"
      ofelia.job-exec.phpfpm_keycloak_sync.command: "/bin/bash -c \"php /crons/keycloak-sync.php || exit 0\""
      ofelia.job-exec.phpfpm_ldap_sync.schedule: "@every 1m"
      ofelia.job-exec.phpfpm_ldap_sync.no-overlap: "true"
      ofelia.job-exec.phpfpm_ldap_sync.command: "/bin/bash -c \"php /crons/ldap-sync.php || exit 0\""
    networks:
      mailcow-network:
        aliases:
          - phpfpm

  # (Cắt bớt ví dụ - bạn gửi full thì sẽ làm đủ toàn bộ như trên.)

networks:
  mailcow-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-mailcow
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.30.100.0/24
        - subnet: fd4d:6169:6c63:6f77::/64

volumes:
  vmail-vol-1:
  vmail-index-vol-1:
  mysql-vol-1:
  mysql-socket-vol-1:
  redis-vol-1:
  rspamd-vol-1:
  postfix-vol-1:
  crypt-vol-1:
  sogo-web-vol-1:
  sogo-userdata-backup-vol-1:
  clamd-db-vol-1:
